"""
youtube_analytics.py
---------------------
Pulls viewer demographics, geography, watch-time and traffic-source data
via the YouTube Analytics API (OAuth) — separate from youtube_client.py,
which uses YouTube Data API v3 (plain API key) for public video/comment
data. This one only works for channels Tolaram actually owns, and only
once a refresh token has been generated by that channel's owner.

Setup (per brand channel, one-time):
  1. YOUTUBE_ANALYTICS_CLIENT_ID / YOUTUBE_ANALYTICS_CLIENT_SECRET — from
     the OAuth client created in Google Cloud Console.
  2. YOUTUBE_ANALYTICS_REFRESH_TOKEN — generated by the channel owner
     running the one-time authorization script.
All three go in .env. Until they're set, every function here returns a
clean "not configured" result rather than raising.

Note: right now this uses ONE refresh token for ALL brands, which only
works if a single Google account owns/manages every brand's channel. If
different people own different brand channels, this needs one refresh
token per brand instead (YOUTUBE_ANALYTICS_REFRESH_TOKEN_INDOMIE, etc.) —
flag it if that's the case and this gets extended to match.
"""
from __future__ import annotations

import logging
import os
from datetime import datetime, timedelta, timezone
from typing import Dict, List, Optional

from data_store import save_json, load_json

logger = logging.getLogger(__name__)

TOKEN_URI = "https://oauth2.googleapis.com/token"
SCOPES = ["https://www.googleapis.com/auth/yt-analytics.readonly"]

# Same brand -> channel-id env var mapping agent.py uses for the Data API,
# reused here so both features stay in sync without importing agent.py.
_CHANNEL_ENV_KEYS = {
    "Munch It":   "CHANNEL_MUNCHIT",
    "Indomie":    "CHANNEL_INDOMIE",
    "Colgate":    "CHANNEL_COLGATE",
    "Hypo":       "CHANNEL_HYPO",
    "Power Oil":  "CHANNEL_POWER_OIL",
    "Nutrify":    "CHANNEL_NUTRIFY",
    "Lush":       "CHANNEL_LUSH",
    "Minimie":    "CHANNEL_MINIMIE",
}

CACHE_TTL_HOURS = 12  # Analytics API has its own quota — don't refetch on every page load


def channel_id_for_brand(brand: str) -> Optional[str]:
    env_key = _CHANNEL_ENV_KEYS.get(brand)
    if not env_key:
        return None
    val = os.getenv(env_key, "").strip()
    return val if val.startswith("UC") else None


def _configured() -> bool:
    return bool(
        os.getenv("YOUTUBE_ANALYTICS_CLIENT_ID")
        and os.getenv("YOUTUBE_ANALYTICS_CLIENT_SECRET")
        and os.getenv("YOUTUBE_ANALYTICS_REFRESH_TOKEN")
    )


def _get_client():
    """Returns an authenticated youtubeAnalytics v2 client, or None if not configured."""
    if not _configured():
        return None
    try:
        from google.oauth2.credentials import Credentials
        from googleapiclient.discovery import build

        creds = Credentials(
            token=None,
            refresh_token=os.getenv("YOUTUBE_ANALYTICS_REFRESH_TOKEN"),
            token_uri=TOKEN_URI,
            client_id=os.getenv("YOUTUBE_ANALYTICS_CLIENT_ID"),
            client_secret=os.getenv("YOUTUBE_ANALYTICS_CLIENT_SECRET"),
            scopes=SCOPES,
        )
        return build("youtubeAnalytics", "v2", credentials=creds)
    except Exception as e:
        logger.error(f"Failed to build YouTube Analytics client: {e}")
        return None


def _date_range(days: int):
    end = datetime.now(timezone.utc).date()
    start = end - timedelta(days=days)
    return start.isoformat(), end.isoformat()


def _run_report(client, channel_id: str, start: str, end: str,
                 metrics: str, dimensions: str = "", sort: str = "") -> Optional[Dict]:
    try:
        req = client.reports().query(
            ids=f"channel=={channel_id}",
            startDate=start,
            endDate=end,
            metrics=metrics,
            dimensions=dimensions or None,
            sort=sort or None,
        )
        return req.execute()
    except Exception as e:
        logger.warning(f"YouTube Analytics query failed (metrics={metrics}): {e}")
        return None


def _rows_to_dicts(resp: Optional[Dict]) -> List[Dict]:
    if not resp or "columnHeaders" not in resp:
        return []
    cols = [c["name"] for c in resp["columnHeaders"]]
    return [dict(zip(cols, row)) for row in resp.get("rows", [])]


def get_channel_report(brand: str, days: int = 90, force: bool = False) -> Dict:
    """
    Full analytics report for one brand's channel: overview metrics,
    demographics (age/gender), geography, device type, and traffic
    sources. Cached per brand for CACHE_TTL_HOURS to respect the
    Analytics API's own quota.
    """
    cache_file = f"youtube_analytics_{brand.lower().replace(' ', '_')}.json"

    if not force:
        cached = load_json(cache_file, default=None)
        if cached and cached.get("fetched_at"):
            fetched = datetime.fromisoformat(cached["fetched_at"])
            if datetime.now(timezone.utc) - fetched < timedelta(hours=CACHE_TTL_HOURS):
                return cached

    if not _configured():
        return {"ok": False, "reason": "YouTube Analytics API not configured — set YOUTUBE_ANALYTICS_CLIENT_ID/SECRET/REFRESH_TOKEN in .env"}

    channel_id = channel_id_for_brand(brand)
    if not channel_id:
        return {"ok": False, "reason": f"No channel_id configured for brand '{brand}'"}

    client = _get_client()
    if not client:
        return {"ok": False, "reason": "Could not authenticate with YouTube Analytics API — check credentials"}

    start, end = _date_range(days)

    overview_resp = _run_report(
        client, channel_id, start, end,
        metrics="views,estimatedMinutesWatched,averageViewDuration,averageViewPercentage,"
                "subscribersGained,subscribersLost,likes,comments,shares",
    )
    overview_rows = _rows_to_dicts(overview_resp)
    overview = overview_rows[0] if overview_rows else {}

    demographics_resp = _run_report(
        client, channel_id, start, end,
        metrics="viewerPercentage", dimensions="ageGroup,gender",
    )
    demographics = _rows_to_dicts(demographics_resp)

    geography_resp = _run_report(
        client, channel_id, start, end,
        metrics="views,estimatedMinutesWatched", dimensions="country", sort="-views",
    )
    geography = _rows_to_dicts(geography_resp)[:15]  # top 15 countries

    device_resp = _run_report(
        client, channel_id, start, end,
        metrics="views", dimensions="deviceType", sort="-views",
    )
    devices = _rows_to_dicts(device_resp)

    traffic_resp = _run_report(
        client, channel_id, start, end,
        metrics="views", dimensions="insightTrafficSourceType", sort="-views",
    )
    traffic_sources = _rows_to_dicts(traffic_resp)

    result = {
        "ok": True,
        "brand": brand,
        "channel_id": channel_id,
        "date_range": {"start": start, "end": end, "days": days},
        "fetched_at": datetime.now(timezone.utc).isoformat(),
        "overview": overview,
        "demographics": demographics,
        "geography": geography,
        "devices": devices,
        "traffic_sources": traffic_sources,
    }
    save_json(cache_file, result)
    return result